Document: laurux
Title: Debian laurux Manual
Author: <insert document author here>
Abstract: This manual describes what laurux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/laurux/laurux.sgml.gz

Format: postscript
Files: /usr/share/doc/laurux/laurux.ps.gz

Format: text
Files: /usr/share/doc/laurux/laurux.text.gz

Format: HTML
Index: /usr/share/doc/laurux/html/index.html
Files: /usr/share/doc/laurux/html/*.html
