#!/bin/bash
#
# Object : script used to launch laurux
# Author: Freddy Frouin <freddy.frouin@linuxtribe.fr>
# Release : 1.4.10 - options
# Date: Wen Jul 23 18:09:08 2017

release=1.4.10
lauruxrelease=1.4.7
maintenance="Freddy Frouin <freddy@linuxtribe.fr>"

homelink=$HOME/LX.pos

case "$1" in
--help|-h)
	echo "Usage:"
	echo "	$0 -h|--help		Help screen"
	echo "	$0 -v|--version		Version"
	echo
	echo "Don't forget to setup an access to your sql database"
	echo "in order laurux to start up."
	echo
	echo "With mysql, once logged in, you may run something like :"
	echo
	echo "	> CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'new_password';"
	echo "	> GRANT ALL ON Laurux*.* TO 'new_user'@'localhost';"
	echo "	> FLUSH PRIVILEGES;"
	echo
	;;
--version|-v)
	echo "LXPos release for debian systems v$release"
	echo " -> package includes LXPos $lauruxrelease"
	echo " -> support : $maintenance"
	;;
*)
	if [ ! -e $homelink ]; then
		ln -s /usr/share/LX.pos $homelink
	fi

	$HOME/LX.pos/LXPos.gambas && rm $homelink
	;;
esac
