.TH LAURUX 1
.SH NAME
Laurux packaged for debian
.SH SYNOPSIS
.B laurux
command will start the application /usr/share/Laurux3/Laurux3.gambas
.RI [ name ...]
.SH DESCRIPTION
.B Due to the design of the application Laurux,
a link in home directory is required to make it work. This
package allow one installation for multiple users on same host.
