#!/bin/bash
#
# Object : script used to launch laurux
# Author: Freddy Frouin <freddy.frouin@linuxtribe.fr>
# Release : 0.1 - init
# Date: Wen Jul 19 18:09:08 2017

homelink=$HOME/Laurux3

if [ ! -e $homelink ]; then
	ln -s /usr/share/Laurux3 $HOME/Laurux3
fi

$HOME/Laurux3/Laurux3.gambas && rm $homelink
