.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 freddy <freddy@linuxtribe.fr>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LAURUX 1 "July 19, 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Laurux is an application designed for french companies or professional individuals that need an application to manage their business : commercial, billing, french accounting, point of sale.
.SH SYNOPSIS
.B lxpos
has been designed originaly to be deployed in home directory of end users.
This package enable multiuser usage of a single deployment of the lxpos
application.
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBlxpos\fP is a simple wrapper to allow application to get data from user
home directory. A link $HOME/LX.pos is created when lxpos is running.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR http://www.laurux.fr
